=== jvrana/DASi-DNA-Design/dasi/cost/parameter_json_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Cost Parameters Schema",
  "description": "This schema validate a json input for the DASi cost model",
  "type": "object",
  "properties": {
    "global_time_cost": {
      "type": "number",
      "title": "global time cost",
      "description": "the global cost of waiting *1* day"
    },
    "global_material_modifier": {
      "type": "number",
      "title": "global material modifier",
      "description": "multiplies the effect of the material cost by this amount",
      "default": 1,
      "examples": [
        1
      ]
    },
    "primer_min_anneal": {
      "type": "number",
      "minimum": 5,
      "maximum": 99,
      "multipleOf": 1.0,
      "title": "minimum primer anneal",
      "description": "the minimum number of bases to consider for an annealing event",
      "default": 16
    },
    "_primer_min_span": {
      "type": "number",
      "multipleOf": 1.0
    },
    "primer_efficiency": {
      "type": "object",
      "title": "primer efficiency data frame",
      "description": "provides efficiency *homology* for gibson assembly",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "type": "array",
            "items": [
              {"type":  "number", "multipleOf": 1},
              {"type":  "number", "multipleOf": 1},
              {"type":  "number", "maximum": 1}
            ],
            "additionalItems": false
          }
        },
        "columns": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "minItems": 3,
          "maxItems": 3
        }
      },
      "required": [
        "data",
        "columns"
      ],
      "additionalProperties": false
    },
    "primer_cost": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "type": "array",
            "contains": {
              "type": "number"
            },
            "minItems": 6,
            "maxItems": 6
          }
        },
        "columns": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "minItems": 6,
          "maxItems": 6
        }
      },
      "required": [
        "data",
        "columns"
      ],
      "additionalProperties": false
    },
    "synthesis_cost": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "type": "array",
            "minItems": 4,
            "maxItems": 4
          }
        },
        "columns": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "minItems": 4,
          "maxItems": 4
        }
      },
      "additionalProperties": false,
      "required": [
        "data",
        "columns"
      ]
    },
    "_synthesis_step_size": {
      "type": "number",
      "multipleOf": 1.0
    },
    "_synthesis_left_span_range": {
      "type": "array",
      "items": [
        {
          "type": "number",
          "multipleOf": 1.0
        },
        {
          "type": "number",
          "multipleOf": 1.0
        }
      ],
      "additionalItems": false
    }
  },
  "minProperties": 9,
  "maxProperties": 9,
  "additionalProperties": false
}

=== jvrana/DASi-DNA-Design/dasi/cost/default_parameters.json
{
    "global_time_cost": 10.0,
    "global_material_modifier": 1.0,
    "primer_min_anneal": 16,
    "_primer_min_span": -300,
    "primer_efficiency": {
        "data": [
            [0, 10, 0.0],
            [10, 15, 0.3],
            [15, 20, 0.6],
            [20, 30, 0.8],
            [30, 40, 0.9],
            [40, 45, 0.9],
            [45, 50, 0.8],
            [50, 100, 0.75],
            [100, 120, 0.5],
            [120, 150, 0.3],
            [150, 250, 0.1],
            [250, 300, 0.0]
        ],
        "columns": ["min", "max", "efficiency"]
    },
    "primer_cost": {
        "data":  [
            ["IDTPrimer", 16.0, 60.0, 0.0, 0.15, 1.5],
            ["IDTUltramer", 45.0, 200.0, 0.0, 0.40, 1.5]
        ],
        "columns": ["name", "min", "max", "base cost", "cost per bp", "time (days)"]
    },
    "synthesis_cost": {
        "data": [
            [0, 1, 0, 0],
            [1, 100, "inf", "inf"],
            [100, 500, 89.0, 3.0],
            [500, 750, 129.0, 3.0],
            [750, 1000, 149.0, 4.0],
            [1000, 1250, 209.0, 7.0],
            [1250, 1500, 249.0, 7.0],
            [1500, 1750, 289.0, 7.0],
            [1750, 2000, 329.0, 7.0],
            [2000, 2250, 399.0, 7.0]
        ],
        "columns": ["min", "max", "base", "time"]
    },
    "_synthesis_step_size": 10,
    "_synthesis_left_span_range": [-500, 500]
}
